import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const pokemon = api.pokemon.get.useQuery({ name: "ditto" });

  return (
    <>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <div className="shadow-2xl rounded-full">
            {pokemon.data ? (
              <Image
                src={pokemon.data.sprites.front_default}
                width={150}
                height={150}
                alt="Ditto"
              />
            ) : (
              "Loading pokemon..."
            )}
          </div>
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
